#!/bin/bash

#2017-0421
#EggOxygen

#Build Shell For HTC 10

#Build SudaMod
echo "Start Building SudaMod Nougat"

#Copy local_manifest To Source

#Make dir for cache
#mkdir -p  "/media/eggoxygen/Source_Main/CCACHE"

#Breakfast Time
cd "/media/eggoxygen/Source_Main/LOS/SMN"
.  build/envsetup.sh
export WITH_SU=true
export USE_CCACHE=1
export CCACHE_DIR=/media/eggoxygen/Source_Main/CCACHE/
prebuilts/misc/linux-x86/ccache/ccache -M 50G
breakfast pme && croot && brunch pme
