#!/bin/bash

#2017-0317
#EggOxygen

#Fixed Project Not Found

#####################
#LineageOS
echo "Repo LineageOS12.1"
cd '/media/eggoxygen/Source_Main/LOS/LOS121'
repo sync --force-sync --force-broken --no-clone-bundle --no-tags -j12

echo "Repo LineageOS13"
cd '/media/eggoxygen/Source_Main/LOS/LOS13'
repo sync --force-sync --force-broken --no-clone-bundle --no-tags -j12

echo "Repo LineageOS14.1"
cd '/media/eggoxygen/Source_Main/LOS/LOS141'
repo sync --force-sync --force-broken --no-clone-bundle --no-tags -j12
#####################

#####################
#SudaMod
echo "Repo Sudamod Nougat"
cd '/media/eggoxygen/Source_Main/SM/SMN'
repo sync --force-sync --force-broken --no-clone-bundle --no-tags -j12
#####################

