#!/bin/bash

#2017-0311
#EggOxygen

#Don`t Remove CCACHE Dir
#Don`t Need Add Any Exrta

#Build SM_M
echo "Start Building SM_M"
#Sync Lastest Source
# proxychains repo sync
#Clean
echo "Remove Old Files"
rm -rf "/media/eggoxygen/Source_Main/SM_M/device/htc"
rm -rf "/media/eggoxygen/Source_Main/SM_M/device/qcom/common"
rm -rf "/media/eggoxygen/Source_Main/SM_M/kernel"
rm -rf "/media/eggoxygen/Source_Main/SM_M/vendor/htc"
#rm -rf "/media/eggoxygen/Source_Main/CCACHE"
#Copy New Device Files
echo "Copy New Files"
cp -r '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_SM_M/device' '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_SM_M/kernel' '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_SM_M/vendor' '/media/eggoxygen/Source_Main/SM_M'
##Copy Exrta Change To Source
##'/media/eggoxygen/Source_Main/EXRTA/EXRTA_SM_M.sh'
##Make dir for cache
##mkdir -p  "/media/eggoxygen/Source_Main/CCACHE"
#Breakfast Time
cd "/media/eggoxygen/Source_Main/SM_M"
.  build/envsetup.sh
make clean
export WITH_SU=true
export USE_CCACHE=1
export CCACHE_DIR=/media/eggoxygen/Source_Main/CCACHE/
prebuilts/misc/linux-x86/ccache/ccache -M 50G
breakfast b3uhl && croot && brunch b3uhl
##When Build Done ** Restore
##'/media/eggoxygen/Source_Main/EXRTA/RESTORE_SM_M.sh' 
