#!/bin/bash

#2017-0415
#EggOxygen


#Build CM121
echo "Start Building CM121"

#Clean Old Files
echo "Remove Old Files"
rm -rf "/media/eggoxygen/Source_Main/LOS/CM121/device/htc"
rm -rf "/media/eggoxygen/Source_Main/LOS/CM121/device/qcom/common"
rm -rf "/media/eggoxygen/Source_Main/LOS/CM121/kernel"
rm -rf "/media/eggoxygen/Source_Main/LOS/CM121/vendor/htc"
#rm -rf "/media/eggoxygen/Source_Main/CCACHE"

#Copy New Device Files
echo "Copy New Files"
cp -r '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_CM121/device' '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_CM121/kernel' '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_CM121/vendor' '/media/eggoxygen/Source_Main/LOS/CM121'

#Make dir for cache
#mkdir -p  "/media/eggoxygen/Source_Main/CCACHE"

#Breakfast Time
cd "/media/eggoxygen/Source_Main/CM121"
.  build/envsetup.sh
#export WITH_SU=true
export USE_CCACHE=1
export CCACHE_DIR=/media/eggoxygen/Source_Main/CCACHE/
prebuilts/misc/linux-x86/ccache/ccache -M 50G
breakfast b3uhl && croot && brunch b3uhl
