#!/bin/bash

#2017-0415
#EggOxygen


#Build LOS141
echo "Start Building LOS141"

#Clean Old Files
echo "Remove Old Files"
rm -rf "/media/eggoxygen/Source_Main/LOS/LOS141/device/htc/b3-common"
rm -rf "/media/eggoxygen/Source_Main/LOS/LOS141/device/htc/b3uhl"
rm -rf "/media/eggoxygen/Source_Main/LOS/LOS141/kernel/msm8994"
rm -rf "/media/eggoxygen/Source_Main/LOS/LOS141/vendor/htc/b3-common"
#rm -rf "/media/eggoxygen/Source_Main/CCACHE"

#Copy New Device Files
echo "Copy New Files"
cd '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_Nougat'
git checkout CM14.1
cp -r '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_Nougat/device' '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_Nougat/kernel' '/media/eggoxygen/Source/B3UHL_SOURCE/B3UHL_Nougat/vendor' '/media/eggoxygen/Source_Main/LOS/LOS141'

#Make dir for cache
#mkdir -p  "/media/eggoxygen/Source_Main/CCACHE"

#Breakfast Time
cd "/media/eggoxygen/Source_Main/LOS/LOS141"
.  build/envsetup.sh
export WITH_SU=true
export USE_CCACHE=1
export CCACHE_DIR=/media/eggoxygen/Source_Main/CCACHE/
prebuilts/misc/linux-x86/ccache/ccache -M 50G
breakfast b3uhl && croot && brunch b3uhl
